if (self.CavalryLogger) { CavalryLogger.start_js(["ayf1E"]); }

__d("MNCommerceCallToActionType",[],(function a(b,c,d,e,f,g){f.exports={OPEN_NATIVE:1,OPEN_URL:2,OPEN_CANCEL_RIDE_MUTATION:3,POSTBACK:4,ACCOUNT_LINK:5,MANAGE_MESSAGES:6,SHARE:7,PAYMENT:8,FACEBOOK_REPORT_A_PROBLEM:9,SUBSCRIPTION_PRESELECT:10,NAVIGATION:11,EXTENSIBLE_SHARE:12,OPEN_REACT_NATIVE_MINI_APP:13,OPEN_PAGE_ABOUT:14};}),null);